### ISSUE TITLE
bug: Validation of events in saveEvents suffers from coercion issue

### ISSUE THREAD

**Issue by lorenzleutgeb** [thenativeweb/wolkenkit-eventstore#9]
Hello!

This bug affects the PostreSQL implementation, but it might be the case that other implementations are affected as well.

When someone calls `saveEvents({ events: [] })`, this will result in an error similar to:

```
syntax error at or near "RETURNING"!
```

This error is not obvious to debug. The reason for it is that in case `events == []` you will have `placeholders == []` and will [join an empty array ](https://github.com/thenativeweb/wolkenkit-eventstore/blob/a081c78e899e8def2b7151c84ba6fed4a9b7b393/src/postgres/Eventstore.js#L268) which results in a malformed SQL statement.

The root cause is an error in [validating `events`](https://github.com/thenativeweb/wolkenkit-eventstore/blob/a081c78e899e8def2b7151c84ba6fed4a9b7b393/src/postgres/Eventstore.js#L235). Plain and simple, in JavaScript, `[]` is coerced to `true`, which can be verified as follows:

```
$ echo '!![]' | node -i
> !![]
true
```

A correct check in this case would be to use [`isArray`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/isArray) as follows:

```js
Array.isArray(events) && events.length > 0
```

**Comment by goloroden** [comment]
Hi @lorenzleutgeb 😊 

Thanks once again for reporting this issue, and for also taking the time to search for the root cause of the problem! I'm currently fixing the issue, so this shouldn't be an issue any more in the near future 😊 

Once again, thanks for your great help!
